site_name: Stream Processing
nav:
    - Home: index.md
    - Frameworks:
        - frameworks/kafka.md
    - Tools:
        - tools/kafkacat.md
    - About: about.md
theme:
    name: cinder
google_analytics:
  - G-27GF7GECYX
  - auto
